@extends('layouts.app')
@section('content')
    @include('app.banner.slider-banner')
    @include('app.home.feature')
    @include('app.home.category')
    @include('app.product.product_list')
    @include('app.home.exclusive-deal')
    @include('app.product.product-related')
@endsection
